apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}-dapr
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: localhost
  ports:
  - port: 3500
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "gateway.fullname" . }}-dapr
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`api.kubefox.io`)
    services:
    - name: {{ include "gateway.fullname" . }}-dapr
      port: 3500