apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  secretName: http-gateway-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - "xigxog.io"
  - "*.kubefox.io"
