apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: http-gateway
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.kubefox.io"
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*.kubefox.io"
    tls:
      mode: SIMPLE # enables HTTPS on this port
      credentialName: http-gateway-cert
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: docker-gateway
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 5000
      name: docker
      protocol: HTTPS
    hosts:
    - "*.kubefox.io"
    tls:
      mode: SIMPLE # enables HTTPS on this port
      credentialName: http-gateway-cert
