repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: coredns
    url: https://coredns.github.io/helm
  - name: dapr
    url: https://dapr.github.io/helm-charts
  - name: fluent
    url: https://fluent.github.io/helm-charts
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: metrics-server  
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: nats
    url: https://nats-io.github.io/k8s/helm/charts
  - name: opensearch
    url: https://opensearch-project.github.io/helm-charts
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts
  - name: timescale
    url: https://charts.timescale.com
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: twun
    url: https://helm.twun.io

releases:
  - name: coredns
    chart: coredns/coredns
    version: "1.16.5"
    namespace: kube-system
    values:
      - values/coredns.yaml
    labels:
      group: core

  - name: metallb
    chart: bitnami/metallb
    version: "2.6.2"
    namespace: kube-system
    values:
      - values/metallb.yaml
    labels:
      group: core

  - name: local-ssd
    chart: ./charts/local-path-provisioner
    namespace: kube-system
    values:
      - values/local-ssd.yaml
    labels:
      group: core

  - name: local-hdd
    chart: ./charts/local-path-provisioner
    namespace: kube-system
    values:
      - values/local-hdd.yaml
    labels:
      group: core

  - name: metrics-server
    chart: metrics-server/metrics-server
    version: "3.8.2"
    namespace: kube-system
    values:
      - values/metrics-server.yaml
    labels:
      group: core

  - name: cert-manager
    chart: bitnami/cert-manager
    version: "0.4.4"
    namespace: cert-manager
    values:
      - values/cert-manager.yaml
    labels:
      group: cert

  - name: cert-issuer
    chart: ./charts/cert-issuer
    namespace: cert-manager
    values:
      - secrets/cert-issuer.yaml
    needs:
      - cert-manager
    labels:
      group: cert

  - name: docker-registry
    chart: twun/docker-registry
    version: "2.1.0"
    namespace: registry
    values:
      - values/docker-registry.yaml
      - secrets/docker-registry.yaml
    labels:
      group: registry

  - name: metacontroller
    chart: ./charts/metacontroller
    namespace: metacon-system
    values:
      - values/metacontroller.yaml
    labels:
      group: controller

  - name: dapr
    chart: dapr/dapr
    version: "1.6.0"
    namespace: dapr-system
    values:
      - values/dapr.yaml
    labels:
      group: dapr

  # Should break this into individual charts
  # Take a look at https://github.com/kubernetes-sigs/prometheus-adapter instead of metrics server?
  - name: monitoring
    chart: ./charts/monitoring
    namespace: telemetry
    labels:
      group: telemetry

  - name: prometheus
    chart: prometheus/kube-prometheus-stack
    version: "33.0.0"
    namespace: telemetry
    values:
      - values/prometheus-stack.yaml
    needs:
      - monitoring
    labels:
      group: telemetry

  - name: opensearch
    chart: opensearch/opensearch
    version: "1.7.4"
    namespace: telemetry
    values:
      - values/opensearch.yaml
    labels:
      group: telemetry

  - name: opensearch-dashboards
    chart: opensearch/opensearch-dashboards
    version: "1.2.0"
    namespace: telemetry
    values:
      - values/opensearch-dashboards.yaml
    labels:
      group: telemetry

  - name: fluent-bit
    chart: fluent/fluent-bit
    version: "0.19.18"
    namespace: telemetry
    values:
      - values/fluent-bit.yaml
    labels:
      group: telemetry

  - name: nats
    chart: nats/nats
    version: "0.13.1"
    namespace: nats
    values:
      - values/nats.yaml
    labels:
      group: nats

  - name: traefik
    chart: traefik/traefik
    version: "10.14.1"
    namespace: apigateway
    values:
      - values/traefik.yaml
    labels:
      group: ingress
###
# EXPERIMENTS
###

# - name: fission
#   url: https://fission.github.io/fission-charts
# - name: grafana
#   url: https://grafana.github.io/helm-charts
# - name: ingress-nginx
#   url: https://kubernetes.github.io/ingress-nginx
# - name: istio
#   url: https://istio-release.storage.googleapis.com/charts
# - name: juicefs-csi-driver
#   url: https://juicedata.github.io/juicefs-csi-driver
# - name: kiali
#   url: https://kiali.org/helm-charts
# - name: longhorn
#   url: https://charts.longhorn.io
# - name: metallb
#   url: https://metallb.github.io/metallb
# - name: pingcap
#   url: https://charts.pingcap.org/

# - name: longhorn
#   chart: longhorn/longhorn
#   version: "1.2.3"
#   namespace: longhorn-system
#   values:
#   - values/longhorn.yaml
#   labels:
#     group: storage

# - name: juicefs
#   chart: juicefs-csi-driver/juicefs-csi-driver
#   version: "0.8.1"
#   namespace: juicefs-system
#   values:
#   - values/juicefs.yaml
#   labels:
#     group: storage

# # Need crds first
# # kubectl create -f https://raw.githubusercontent.com/pingcap/tidb-operator/master/manifests/crd.yaml
# - name: tidb-operator
#   chart: pingcap/tidb-operator
#   version: "1.3.1"
#   namespace: ti-system
#   values:
#   - values/tidb-operator.yaml
#   labels:
#     group: kv

# - name: istio-base
#   chart: istio/base
#   version: "1.12.1"
#   namespace: istio-system
#   values:
#   - values/istio-base.yaml

# - name: istiod
#   chart: istio/istiod
#   version: "1.12.1"
#   namespace: istio-system
#   labels:
#     group: istio
#   values:
#   - values/istiod.yaml

# - name: istio-ingress
#   chart: istio/gateway
#   version: "1.12.1"
#   namespace: istio-system
#   labels:
#     group: istio
#   values:
#   - values/istio-ingress.yaml

# - name: gateway
#   chart: ./charts/gateway
#   namespace: istio-system
#   labels:
#     group: istio

# - name: kiali
#   chart: kiali/kiali-server
#   version: "1.44.0"
#   namespace: istio-system
#   labels:
#     group: istio
#   values:
#   - values/kiali-server.yaml

# - name: consul
#   chart: hashicorp/consul
#   version: "1.5.0"
#   namespace: consul
#   values:
#   - values/consul.yaml

# - name: fission-crds
#   chart: ./charts/fission-crds
#   namespace: fission
#   labels:
#     group: runtime
#     crds: "true"

# - name: fission
#   chart: fission/fission-all
#   version: "v1.14.1"
#   namespace: fission
#   labels:
#     group: runtime
#   values:
#   - values/fission.yaml

# - name: functions
#   chart: ./charts/functions
#   namespace: fission
#   labels:
#     group: runtime

# - name: nginx-ingress
#   chart: bitnami/nginx-ingress-controller
#   version: "9.1.5"
#   namespace: kube-system
#   values:
#   - values/nginx-ingress-controller.yaml
#   labels:
#     group: ingress

# - name: ingress-nginx
#   chart: ingress-nginx/ingress-nginx
#   version: "4.0.17"
#   namespace: kube-system
#   values:
#   - values/ingress-nginx.yaml
#   labels:
#     group: ingress
# - name: timescaledb
#   chart: timescale/timescaledb-single
#   # chart: ./charts/timescaledb-single
#   version: "0.10.0"
#   namespace: telemetry
#   values:
#     - values/timescaledb.yaml
#   labels:
#     group: telemetry

# - name: promscale
#   chart: timescale/promscale
#   # chart: ./charts/timescaledb-single
#   version: "0.10.0"
#   namespace: telemetry
#   values:
#     - values/promscale.yaml
#   labels:
#     group: telemetry
