environments:
  default: {}
  ha: {}

releases:
  - name: local-ssd
    chart: ./charts/local-path-provisioner
    namespace: kube-system
    values:
      - values/local-ssd.yaml

  - name: local-hdd
    chart: ./charts/local-path-provisioner
    namespace: kube-system
    values:
      - values/local-hdd.yaml

  - name: kubefox
    chart: ../charts/kubefox
    namespace: kubefox-system
    values:
      - values/kubefox.yaml
      - values/kubefox-{{ .Environment.Name }}.yaml
    needs:
      - kube-system/local-ssd
      - kube-system/local-hdd
