apiVersion: v2
type: application
version: 0.1.1
appVersion: "0.1.0"

name: kubefox
description: A Helm chart for the KubeFox Platform.

dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: "v1.7.1"
  - name: dapr
    repository: https://dapr.github.io/helm-charts
    version: "1.6.0"
  - name: fluent-bit
    repository: https://fluent.github.io/helm-charts
    version: "0.19.20"
  - name: nats
    repository: https://nats-io.github.io/k8s/helm/charts
    version: "0.13.2"
  - name: opensearch
    repository: https://opensearch-project.github.io/helm-charts
    version: "1.8.3"
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: "33.2.0"
    alias: prometheus
  - name: traefik
    repository: https://helm.traefik.io/traefik
    version: "10.14.2"