apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: timescaledb-certificate
spec:
  secretName: timescaledb-certificate
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - "timescaledb.kubefox.io"
---
apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-credentials
type: Opaque
data:
  PATRONI_SUPERUSER_PASSWORD: "YWRtaW4="
  PATRONI_REPLICATION_PASSWORD: "YWRtaW4="
  PATRONI_admin_PASSWORD: "YWRtaW4="