---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juicefs-s3-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: juicefs-s3-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: juicefs-s3-gateway
    spec:
      initContainers:
        - name: format
          image: juicedata/juicefs-csi-driver:v0.12.0
          command:
            - sh
            - -c
            - juicefs format --storage=${storage} --bucket=${bucket} --access-key=${accesskey} --secret-key=${secretkey} ${metaurl} ${name}
          envFrom:
            - secretRef:
                name: juicefs-secret
          # env:
          #   - name: accesskey
          #     valueFrom:
          #       secretKeyRef:
          #         name: juicefs-secret
          #         key: access-key
          #   - name: secretkey
          #     valueFrom:
          #       secretKeyRef:
          #         name: juicefs-secret
          #         key: secret-key
      containers:
        - name: gateway
          image: juicedata/juicefs-csi-driver:v0.12.0
          command:
            - sh
            - -c
            - juicefs gateway ${METAURL} 0.0.0.0:9000 --metrics=0.0.0.0:9567
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: METAURL
              valueFrom:
                secretKeyRef:
                  name: juicefs-secret
                  key: metaurl
            - name: MINIO_ROOT_USER
              value: admin
              # valueFrom:
              #   secretKeyRef:
              #     name: juicefs-secret
              #     key: access-key
            - name: MINIO_ROOT_PASSWORD
              value: password
              # valueFrom:
              #   secretKeyRef:
              #     name: juicefs-secret
              #     key: secret-key
          ports:
            - containerPort: 9000
            - containerPort: 9567
          resources:
            limits:
              cpu: 5000m
              memory: 5Gi
            requests:
              cpu: 250m
              memory: 1Gi
