certmanager: {}

dapr: {}

fluentbit: {}

metacontroller: {}

nats:
  nats:
    jetstream:
      memStorage:
        size: 1Gi
      fileStorage:
        size: 16Gi
        storageClassName: ssd

  natsbox:
    enabled: true

opensearch:
  persistence:
    size: 32Gi
    storageClass: hdd

prometheus:
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: ssd
            resources:
              requests:
                storage: 4Gi

traefik: {}
