---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubefox.fullname" . }}-github-runner-secrets
  labels:
    app.kubernetes.io/component: github-runner
    {{- include "kubefox.labels" . | nindent 4 }}  
type: Opaque
data:
  ACCESS_TOKEN: {{ .Values.githubRunner.access_token |b64enc}}
  CNB_REGISTRY_AUTH: {{ .Values.githubRunner.registry_auth | toJson | quote |b64enc }}