{{ if .Values.githubRunner.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubefox.fullname" . }}-github-runner
  labels:
    app.kubernetes.io/component: github-runner
    {{- include "kubefox.labels" . | nindent 4 }}  
type: Opaque
data:
  ACCESS_TOKEN: {{ .Values.githubRunner.accessToken | b64enc}}
  CNB_REGISTRY_AUTH: {{ .Values.githubRunner.registryAuth | toJson | quote | b64enc }}
{{- end }}