apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cert-issuer.fullname" . }}-cloudflare-token
  labels:
    {{- include "cert-issuer.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.apiToken | quote }}