---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-config
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      # Mounted `metricbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: false
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      ssl:
        verification_mode: none
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-modules
data:
  prometheus.yml: |-
    - module: prometheus
      metricsets: ["remote_write"]
      host: "localhost"
      port: "9201"
    # - module: prometheus
    #   period: 1s
    #   # metricsets: ["collector"]
    #   hosts: ["localhost:9090"]
    #   metrics_path: /federate
    #   query:
    #     'match[]': '{job="node-exporter"}'
