{{- if and .Values.collector.enabled .Values.global.deployKubefox }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "kubefox.fullname" . }}-collector
  labels:
    app.kubernetes.io/component: collector
    {{- include "kubefox.labels" . | nindent 4 }}
stringData:
  fluent-bit.conf: |
    {{- tpl .Values.collector.logs.config . | nindent 4 }}
  jaeger-collector.yaml: |
    {{- tpl (toYaml .Values.collector.traces.config) . | nindent 4 }}
  metricbeat.yaml: |
    {{- tpl (toYaml .Values.collector.metrics.config) . | nindent 4 }}
  modules.yaml: |
    {{- tpl (toYaml .Values.collector.metrics.modules) . | nindent 4 }}
{{- end }}