---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat
  labels:
    {{- include "kubefox.labels" . | nindent 4 }}
data:
  metricbeat.yml: |
    {{- (tpl .Values.prometheus.metricbeat.config .) | nindent 4 }}
  modules.yml: |
    {{- (tpl .Values.prometheus.metricbeat.modules .) | nindent 4 }}
